### ISSUE TITLE
Closing the browser

### ISSUE THREAD

**Issue by TwerkyMan** [Elringus/UnityGoogleDrive#35]
Hello again. Right now I have just one bug left to erase, before this plugin starts working perfectly (for me at least), so because of that, I'm here to ask for help. You see, when I click login and don't click Accept nor Deny, everything seems okay, but if I try to click Login one more time, it just doesn't do anything. I can click the Login button in my application as much as I want, but literally nothing happens. I wonder if you know what could cause this type of behavior? Thanks in advance.

**Comment by Elringus** [comment]
Can you please specify which buttons you're referring to? If it's something inside your app, that I'll need to know what exactly they're doing.

**Comment by TwerkyMan** [comment]
I click the "Login" button on my application which basically should send the Get request. Then the browser opens. I close the browser, get back to my application and click the "Login" button again. And then nothing happens. Hope this helps.

**Comment by TwerkyMan** [comment]
Yes, this happens both on editor and on mobile device. Where can I find the logs?

**Comment by Elringus** [comment]
For android use [adb utility](https://developer.android.com/studio/command-line/adb) and for editor you can just copy the console output.

**Comment by TwerkyMan** [comment]
I will try to use adb Utility tomorrow. This is interesting - the console doesn't show any errors either.

**Comment by Elringus** [comment]
I was able to reproduce the issue. The problem is that if an auth session is requested, but not completed, any consequent requests would just continue to wait for it to finish. I've made `AuthController` class static and added a way to cancel pending auth. You can invoke it before running an auth request to make sure it will start a new auth session. Here is an example: https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/Scripts/TestAboutGet.cs#L51

**Comment by TwerkyMan** [comment]
Thank you very much!
