### ISSUE TITLE
Making requests from Oculus GO

### ISSUE THREAD

**Issue by Aupuma** [Elringus/UnityGoogleDrive#43]
Hi, I'm creating an app for Oculus GO (Android) and I'm using the plugin to download some images  and use them as slides for a presentation. When I do the listRequest it opens the online browser and opens the Google login page, when logged it says the app needs offline access.

When I click Allow it gets back to Google and I have to reopen manually the app, but the list is not visible. As it is a special type of Android it may need a different type of callback to get the information correctly... Any ideas?

**Comment by Elringus** [comment]
Hi! In case it re-directs to google.com after the consent screen, most likely either the auth or the app in the developer panel is not setup correctly; it also could be due to out-of-date native libs or errors in the java middleware. Try reading device logs (via ADB utility) during the auth to find more info.
