### ISSUE TITLE
Unable to use it with the PC standalone game

### ISSUE THREAD

**Issue by vipin8169** [Elringus/UnityGoogleDrive#9]
I am using this asset package to upload the data on my google drive. It is working in the editor, I am able to upload all the files when playing the game in Editor. But it doesn't work with the PC standalone build. When I played the exe file, the screen got stuck and and in browser a page was opened (behind the scenes) to ask for permissions. Usually I would expect the browser window to be popped up so that I be able to grant permissions, but no such thing happened. Instead my game screen froze and ultimately I had to force quit. This happens everytime I run the game, even if I have already given the permission by visiting this [URL](https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=192933078191-b6nuqg3lph8t4g4smfmiriqrlpcvelpc.apps.googleusercontent.com&as=SLbHvF-UvXHbSsZCbfvVpg&nosignup=1&destination=http%3A%2F%2F127.0.0.1%3A65401&approval_state=!ChREODhsNEFYcGE0WlcyVDR5ZU11cRIfNDNTTkphVy1tU0lZb1Bud0gtVkU1UUcyUmRFZkxCWQ%E2%88%99AB8iHBUAAAAAWtK5M89IyWyZKHzERgFh-ozA-rkI8g2R&xsrfsig=AHgIfE8qPYJUhvC3OuKB-wzRoOV-WuyaGQ&flowName=GeneralOAuthFlow)

**Comment by vipin8169** [comment]
And this problem is recurrent. When playing for the first time, game asks permission to send data over firewall and then the in browser oauth permission and in the subsequent runs it asks for just the oauth in browser. Is there any workaround this problem?

**Comment by Elringus** [comment]
The application being "frozen" while it waits for the auth token is expected behavior because the http listener blocks the main thread. Probably, this could be improved by using an async listener. I've added an [issue](https://github.com/Elringus/UnityGoogleDrive/issues/10) for this improvement. 

What is not expected, though, is that the browser window is opened "behind the scenes" and not on top of the application. I guess there is something wrong with the OS environment; the window had "popped up" normally on several Windows machines I've tested.

In your SO question you've mentioned uploading user's data to your google drive:
> I am trying to upload the txt files generated during gameplay (whosoever plays it, wherever) to be uploaded to MY google drive.

As stated in the FAQ, that is not possible (by design). User can only work with either their own google drive or a team drive. What you can do, though, is share a folder for the users you wish to upload their data. If the user will add this shared folder to their drive, they will be able to use it as their own (from the viewpoint of the API).

**Comment by vipin8169** [comment]
Oh, it is not useful for me then :(
I need the people to submit the in-game survey files to my google drive so that I can access them later. Is there any other way to accomplish this task? people uploading it to their google drive is not useful for me, as I won't be able to access them. There will be at least 200 participants who all will be anonymous  whose txt files I 'd need to be uploaded on my google drive.

**Comment by Elringus** [comment]
I'm afraid this solution won't really fit this case. I guess you'll need some sort of database here or just use an API for some survey services.
